### ISSUE TITLE
Please fix these Problems 😔🙏

### ISSUE THREAD

**Issue by Kira0116** [phisher98/HindiProviders#78]
1.Streamwish servers are not loading in **https://streamblasters.pm/**

2.**https://toonstream.day/**  Thumbnails are not showing up there are like black or white

3.MDHDtv ( nowmetv ) site is working completely fine it just not working in CS please look into this
**https://nowmetv.net/**

**Comment by Kira0116** [comment]
I think these are the best sites for movies, anime, and live TV in multiple languages, so please keep them updated regularly. Thank you! 😊👍.

**Comment by sosilly2004** [comment]
3rd request already discussed in #73

**Comment by phisher98** [comment]
My Machine is busted right now so need to wait till it will get fixed can't do anything

**Comment by phisher98** [comment]
Most of It is Fixed let me know if you get any other issue

**Comment by Kira0116** [comment]
• Toonstream still shows retry connection 
• Tooniboy old cartoons like Doraemon, ben 10 shows "no links" 
• This is not a request but blasters and multimovies servers has subtitles but doesn't shows up in c.s so please look into if you can 
Thanks for doing all these🙏 😍

**Comment by phisher98** [comment]
Can u send me the link where Multimovies have subtitles?

**Comment by Kira0116** [comment]
> Can u send me the link where Multimovies have subtitles?

https://multimovies.online/movies/the-goat-life/
The goat life , the boys, mirzapur almost every movie have it

**Comment by phisher98** [comment]
That needs changes in Extractors so I can only look at it once laptop repaired
