### ISSUE TITLE
Plugin not working properly

### ISSUE THREAD

**Issue by Politecoder** [phisher98/HindiProviders#93]
Hi brother, hope doing well, just wanted to request please add vidhide server too in the multimovies plugin, if you try to play latest movies like bad news and Kalki 2898ad, they are not playing, hope you fix it.
Have a great day !

**Comment by phisher98** [comment]
Fixed and Working Properly try to reload links sometimes if it doesn't load any link's

**Comment by Politecoder** [comment]
Thanks for replying but I tried a lot, new movies are still not able to play

**Comment by phisher98** [comment]
![Screenshot_2024-07-25-21-34-12-254_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/563c0997-366b-4201-a163-58ae5d739428)

![Screenshot_2024-07-25-21-33-39-992_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/242627a2-2ca4-413c-90dc-3c287bf7cade)

**Comment by phisher98** [comment]
Make sure you are on Pre release

**Comment by Politecoder** [comment]
Thanks brother I just updated to prerelease
